import { Component } from '@angular/core';
import { BreakpointObserver, Breakpoints } from '@angular/cdk/layout';
import { Observable } from 'rxjs';
import { map, shareReplay, tap } from 'rxjs/operators';

@Component({
  selector: 'cx-main-layout',
  templateUrl: './main-layout.component.html',
  styleUrls: ['./main-layout.component.scss']
})
export class MainLayoutComponent {

  isSmallToMedium$: Observable<boolean> = this.breakpointObserver.observe([
    Breakpoints.XSmall,
    Breakpoints.Small,
    Breakpoints.Medium,
  ])
    .pipe(
      map(result => result.matches),
      // TODO: remove tap
      // tap(match => console.log(match)),
      shareReplay()
    );

  constructor(private breakpointObserver: BreakpointObserver) {}

}

// NOTE: see here for breakpoints info:
// https://material.io/design/layout/responsive-layout-grid.html#breakpoints

// TODO: remove - for temporary reference - previously, generated by Mat CLI
// isHandset$: Observable<boolean> = this.breakpointObserver.observe(Breakpoints.Handset)
//     .pipe(
//       map(result => result.matches),
//       tap(match => console.log(match)),
//       shareReplay()
//     );
